### ISSUE TITLE
今天扫描登陆就报下面错误

### ISSUE THREAD

**Issue by fanly** [stonexer/wechatBot#16]
wechat Error: 你登出了微信
    at /Users/wuhaiping/git/learning/new_weixin/wechatBot/node_modules/wechat4u/lib/wechat.js:428:17
    at process._tickCallback (node.js:406:9) +4s
  wxbot Error: 你登出了微信
    at /Users/wuhaiping/git/learning/new_weixin/wechatBot/node_modules/wechat4u/lib/wechat.js:428:17
    at process._tickCallback (node.js:406:9) +1ms
  app 关闭注销连接 +583ms 0

**Comment by spacelan** [comment]
syncCheck同步返回`retcode != 0`就登出微信，偶尔会出现，还没找出原因

我判断有两种可能，
- 服务器信息没有被更新
- 客户端请求信息的encoding不对

**Comment by stonexer** [comment]
@spacelan 其实在此时的登出状态下，还依然可以 sendMessage。我好像没遇到过第一次登陆就登出的问题，一般是反复实验的时候会遇到。然后我去反复登陆了微信网页版，似乎也有登不上的问题、

**Comment by KevinGong2013** [comment]
QQ群: 609776708

可以用微信号加密码登录哦～
